project:
  type: website

website:
  title: "Smithsonian Data Science Lab"
  image: images/dsl_logo.png
  favicon: images/SI_DSL_logo.png
  twitter-card:
    site: "@SIDataScience"
  open-graph: true
  site-url: https://sidatasciencelab.github.io
  repo-url: https://github.com/sidatasciencelab/sidatasciencelab.github.io
  repo-actions: [edit, issue]
  navbar:
    background: "#FFCD00"
    logo: images/dsl_logo.png
    logo-alt: "Smithsonian Data Science Lab logo"
    title: false
    collapse-below: lg
    right:
      - ideas/index.qmd
      - training/index.qmd
      - viewpoints/index.qmd
      - aivalues/index.qmd
      - text: "About SI-DSL"
        menu: 
        - text: "Who we are"
          href: about-dsl.qmd
        - text: "Publications"
          href: publications.qmd
        - text: "Collaborators"
          href: collaborators.qmd
        - text: "Contact us"
          href: contact.qmd
#  sidebar: 
#    - title: "About us"
#      contents:
#        - about-rwds.qmd
#        - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
#        - rwds-partners.qmd
#        - contact.qmd
#        - ts-and-cs.qmd
#    - title: "Call for contributions"
#      contents:
#        - contributor-docs/call-for-contributions.qmd
#        - contributor-docs/case-studies.qmd
#        - contributor-docs/explainers.qmd
#        - contributor-docs/exercises.qmd
#        - contributor-docs/datasets.qmd
#        - contributor-docs/training-guides.qmd
#        - contributor-docs/recommender.qmd
#        - contributor-docs/datasciencebites.qmd
#        - contributor-docs/contributor-guidelines.qmd
#        - contributor-docs/style-guide.qmd
#    - title: "Careers"
#      contents:
#        - careers/index.qmd
#        - careers/career-profiles/index.qmd
#    - title: "Ideas"
#      contents:
#        - ideas/index.qmd
#        - ideas/tutorials/index.qmd
#        - ideas/datasciencebites/index.qmd
#    - title: "Viewpoints"
#      contents: 
#        - viewpoints/index.qmd
#        - viewpoints/editors-blog/index.qmd
#        - viewpoints/interviews/index.qmd
#        - href: viewpoints/newsletter/index.qmd
#          text: Newsletter

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2023 [Smithsonian](https://www.si.edu/)
    center:  
      - href: https://github.com/sidatasciencelab
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/SIDataScience
        icon: twitter
        aria-label: Twitter
    right: |
      [Terms of Use](https://www.si.edu/Termsofuse)

format:
  html:
    theme: [lux, dsl.scss]
    css: dsl.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
