project:
  type: website

website:
  title: "Smithsonian Data Science Lab"
  image: images/dsl_logo.png
  favicon: images/si_favicon.ico
  twitter-card:
    site: "@SIDataScience"
  open-graph: true
  site-url: https://sidatasciencelab.github.io
  repo-url: https://github.com/sidatasciencelab/sidatasciencelab.github.io
  repo-actions: [edit, issue]
  navbar:
    background: "#FFCD00"
    logo: images/dsl_logo.png
    logo-alt: "Smithsonian Data Science Lab logo"
    title: false
    collapse-below: lg
    right:
      - research/index.qmd
      - training/index.qmd
      - news/index.qmd
      - aivalues/index.qmd
      - text: "About SI-DSL"
        menu: 
        - text: "Who we are"
          href: about-dsl.qmd
        - text: "Publications"
          href: publications.qmd
        - text: "Collaboration"
          href: collaborators.qmd
        - text: "Contact us"
          href: contact.qmd

  page-navigation: true

  page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2023 [Smithsonian](https://www.si.edu/)
    center:  
      - href: https://github.com/sidatasciencelab
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/SIDataScience
        icon: twitter
        aria-label: Twitter
    right: |
      [Terms of Use](https://www.si.edu/Termsofuse)

format:
  html:
    theme: [lux, dsl.scss]
    css: dsl.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
